language: node_js

node_js:
    - "node"

sudo: false

env:
    global:
        - MOZ_HEADLESS=1

addons:
    firefox: latest

before_install:
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz"
    - "mkdir geckodriver"
    - "tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver"
    - "export PATH=$PATH:$PWD/geckodriver"
    - npm install -g forever

git:
    submodules: false

before_script:
    - npm install

script:
    - forever start -c "npm start" ./
    - npm test

after_script:
    - forever stopall
