language: node_js

node_js:
    - "node"

sudo: false

env:
    global:
        - MOZ_HEADLESS=1

addons:
    firefox: latest

before_install:
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz"
    - "mkdir geckodriver"
    - "tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver"
    - "export PATH=$PATH:$PWD/geckodriver"

git:
    submodules: false

before_script:
    - npm install
    - npm start

script:
    - npm test
